"""Create initial game schema with Tanda 1 components and nullable loot_table_id for Dano

Revision ID: 7e860a253856
Revises: 
Create Date: 2025-07-18 22:59:22.266892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e860a253856'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salud_actual', sa.Integer(), nullable=False),
    sa.Column('salud_max', sa.Integer(), nullable=False),
    sa.Column('loot_table_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacidad_slots', sa.Integer(), nullable=False),
    sa.Column('capacidad_peso_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criaturaviva_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hambre_actual', sa.Integer(), nullable=False),
    sa.Column('hambre_max', sa.Integer(), nullable=False),
    sa.Column('dano_ataque_base', sa.Integer(), nullable=False),
    sa.Column('velocidad_movimiento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_danio', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_danio'], ['dano.id'], ),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_danio'),
    sa.UniqueConstraint('id_inventario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('criaturaviva_base')
    op.drop_table('inventario')
    op.drop_table('dano')
    # ### end Alembic commands ###
